config/routes.rb
EligibleRailsDemo::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resource :settings, only: [:edit, :update]

  resources :providers
  resources :enrollments
  resource :demographics, only: [:new, :create]
  resource :coverage, only: [:new, :create], controller: :coverage
  resources :claims, only: [:index]
  resources :tickets
  resource :x12, only: [:new, :create], controller: :x12

  resources :payers, only: [:index]
  resources :service_types, only: [:index]

  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/payer.rb
class Payer < ActiveRecord::Base
  has_many :payer_names, dependent: :destroy
  validates :payer_id, presence: true, uniqueness: true

  accepts_nested_attributes_for :payer_names, reject_if: :all_blank, allow_destroy: true
end

app/models/payer_name.rb
class PayerName < ActiveRecord::Base
  belongs_to :payer


end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user

  validates :npi, presence: true, uniqueness: { scope: :user_id }
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  validates :service_type_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :providers, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :api_key, uniqueness: true
  validates :api_key, presence: true, on: :update

  def ready_for_api_calls?
    !api_key.blank?
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_filter :authenticate_user!, :ask_for_api_key
end

app/controllers/coverage_controller.rb
class CoverageController < ApplicationController
  before_filter :authenticate_user!, :ask_for_api_key

  def new
    @coverage = Eligible::Coverage.new
    @coverage.service_type = '30'
  end

  def create
    @coverage = Eligible::Coverage.new(coverage_params)
    @coverage.api_key = current_user.api_key

    if @coverage.valid?
      begin
        @raw_json = RestClient.get(ELIGIBLE_COVERAGE_URL, params: @coverage.to_hash(false))
        @json = JSON(@raw_json)
        if @json['error']
          flash[:warning] = @json['error']['reject_reason_description'].presence
        else
          @full_name = parse_full_name(@json)
          @dob = parse_dob(@json)
          @address = parse_address(@json)
          @plan_coverage = parse_plan_coverage(@json)
          @plan = parse_plan(@json)
          @payer_type = nil
          @plan_remaining = parse_plan_remaining(@json)
          @service = parse_service(@json, @coverage.service_type)
          @service_remaining = parse_service_remaining(@json, @coverage.service_type)
        end
      rescue Exception => ex
        flash[:warning] = ex.message
      end
    end

    render :new
  end

  private

  def parse_full_name(json)
    first_name = json['demographics']['subscriber']['first_name'].presence.humanize
    last_name = json['demographics']['subscriber']['last_name'].presence.humanize
    "#{first_name} #{last_name}"
  end

  def parse_dob(json)
    json['demographics']['subscriber']['dob']
  end

  def parse_address(json)
    address = {}
    address[:street] = [json['demographics']['subscriber']['address']['street_line_1']]
    address[:street] << json['demographics']['subscriber']['address']['street_line_2'] if json['demographics']['subscriber']['address']['street_line_2']
    address[:city] = json['demographics']['subscriber']['address']['city']
    address[:state] = json['demographics']['subscriber']['address']['state']
    address[:zip] = json['demographics']['subscriber']['address']['zip']
    address
  end

  def parse_plan_coverage(json)
    {
      active: %w(1 2 3 4 5).include?(json['plan']['coverage_status']),
      description: json['plan']['coverage_status_label']
    }
  end

  def parse_plan(json)
    {
      name: json['plan']['plan_name'],
      number: json['plan']['plan_number'],
      group_name: json['plan']['group_name']
    }
  end

  def parse_plan_remaining(json)
    financials = json['plan']['financials']
    {
      deductible: {
        in_network: (financials['deductible']['remainings']['in_network'].collect { |item| { amount: item['amount'], level: item['level'] } } rescue []),
        out_network: (financials['deductible']['remainings']['out_network'].collect { |item| { amount: item['amount'], level: item['level'] } } rescue [])
      },
      stop_loss: {
        in_network: (financials['stop_loss']['remainings']['in_network'].collect { |item| { amount: item['amount'], level: item['level'] } } rescue []),
        in_network: (financials['stop_loss']['remainings']['in_network'].collect { |item| { amount: item['amount'], level: item['level'] } } rescue [])
      }
    }
  end

  def parse_service(json, service_code)
    service = json['services'].detect { |s| s['type'].to_s == service_code.to_s }
    if service
      { type: service['type'],
        label: service['type_label'],
        active: %w(1 2 3 4 5).include?(service['coverage_status']),
        description: service['coverage_status_label']
      }
    else
      nil
    end
  end


  def parse_service_remaining(json, service_code)
    service = json['services'].detect { |s| s['type'].to_s == service_code.to_s }
    if service
      financials = service['financials']
      {
        deductible: {
          in_network: (financials['deductible']['remainings']['in_network'].collect { |item| { amount: item['amount'], level: item['level'] } } rescue []),
          out_network: (financials['deductible']['remainings']['out_network'].collect { |item| { amount: item['amount'], level: item['level'] } } rescue [])
        },
        stop_loss: {
          in_network: (financials['stop_loss']['remainings']['in_network'].collect { |item| { amount: item['amount'], level: item['level'] } } rescue []),
          in_network: (financials['stop_loss']['remainings']['in_network'].collect { |item| { amount: item['amount'], level: item['level'] } } rescue [])
        }
      }
    else
      nil
    end
  end


  def coverage_params
    params.require(:eligible_coverage).permit(:payer_id, :provider_npi, :provider_first_name, :provider_last_name,
                                              :member_id, :member_first_name, :member_last_name,
                                              :member_dob, :service_type)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :ask_for_api_key, if: :user_signed_in?


end

app/controllers/x12_controller.rb
class X12Controller < ApplicationController
  before_filter :authenticate_user!, :ask_for_api_key

  def new
    @x12 = Eligible::X12.new
  end

  def create
    @x12 = Eligible::X12.new(x12_params)
    @x12.api_key = current_user.api_key

    if @x12.valid?
      begin
        @result = RestClient.get(ELIGIBLE_X12_URL, params: @x12.to_hash(false))
      rescue Exception => ex
        flash[:warning] = ex.message
      end
    end

    render :new
  end

  private

  def x12_params
    params.require(:eligible_x12).permit(:x12)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/coverage_helper.rb
module CoverageHelper
end

app/helpers/demographics_helper.rb
module DemographicsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payers_helper.rb
module PayersHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/x12_helper.rb
module X12Helper
end

app/views/coverage/new.html.erb
<%- content_for :javascript do %>
  <%= javascript_include_tag 'coverage' %>
<%- end %>

<div class="main-content">
  <h1>Coverage</h1>

  <%- if @json && @json['error'].nil? %>
    <h3>Demographics</h3>
    <table class="table table-hover">
      <tr>
        <th>Full Name</th>
        <td><%= @full_name %></td>
      </tr>
      <tr>
        <th>DOB</th>
        <td><%= @dob %></td>
      </tr>
      <tr>
        <th>Street</th>
        <td><%= raw @address[:street].join("<br/>") %></td>
      </tr>
      <tr>
        <th>City</th>
        <td><%= @address[:city] %></td>
      </tr>
      <tr>
        <th>State</th>
        <td><%= @address[:state] %></td>
      </tr>
      <tr>
        <th>ZIP</th>
        <td><%= @address[:zip] %></td>
      </tr>
    </table>

    <h3>Plan</h3>
    <table class="table table-hover">
      <tr>
        <th>Active Plan</th>
        <td><%= @plan_coverage[:active] ? 'Yes' : 'No' %> (<%= @plan_coverage[:description] %>)</td>
      </tr>
      <%- unless @plan[:name].blank? %>
        <tr>
          <th>Plan Name</th>
          <td><%= @plan[:name] %></td>
        </tr>
      <%- end %>
      <%- unless @plan[:group_name].blank? %>
        <tr>
          <th>Group Name</th>
          <td><%= @plan[:group_name] %></td>
        </tr>
      <%- end %>
      <%- if @plan_remaining[:deductible][:in_network].size > 0 %>
        <tr>
          <th>Deductible</th>
          <td>
            <table class="table table-bordered inner-table">
              <%- @plan_remaining[:deductible][:in_network].each do |remaining| %>
                <tr>
                  <th><%= remaining[:level] %></th>
                  <td><%= number_to_currency(remaining[:amount].to_f) %></td>
                </tr>
              <%- end %>
            </table>
          </td>
        </tr>
      <%- end %>
      <%- if @plan_remaining[:stop_loss][:in_network].size > 0 %>
        <tr>
          <th>Stop Loss</th>
          <td>
            <table class="table table-bordered inner-table">
              <%- @plan_remaining[:stop_loss][:in_network].each do |remaining| %>
                <tr>
                  <th><%= remaining[:level] %></th>
                  <td><%= number_to_currency(remaining[:amount].to_f) %></td>
                </tr>
              <%- end %>
            </table>
          </td>
        </tr>
      <%- end %>
    </table>

    <%- if @service %>
      <h3>Service</h3>
      <table class="table table-hover">
        <tr>
          <th>Code</th>
          <td><%= @service[:type] %></td>
        </tr>
        <tr>
          <th>Description</th>
          <td><%= @service[:label] %></td>
        </tr>
        <tr>
          <th>Active</th>
          <td><%= @service[:active] ? 'Yes' : 'No' %> (<%= @service[:description] %>)</td>
        </tr>
        <%- if @service_remaining[:deductible][:in_network].size > 0 %>
          <tr>
            <th>Deductible</th>
            <td>
              <table class="table table-bordered inner-table">
                <%- @service_remaining[:deductible][:in_network].each do |remaining| %>
                  <tr>
                    <th><%= remaining[:level] %></th>
                    <td><%= number_to_currency(remaining[:amount].to_f) %></td>
                  </tr>
                <%- end %>
              </table>
            </td>
          </tr>
        <%- end %>
        <%- if @service_remaining[:stop_loss][:in_network].size > 0 %>
          <tr>
            <th>Stop Loss</th>
            <td>
              <table class="table table-bordered inner-table">
                <%- @service_remaining[:stop_loss][:in_network].each do |remaining| %>
                  <tr>
                    <th><%= remaining[:level] %></th>
                    <td><%= number_to_currency(remaining[:amount].to_f) %></td>
                  </tr>
                <%- end %>
              </table>
            </td>
          </tr>
        <%- end %>        
      </table>
    <%- end %>


    <div style="display: none;" id="raw_json"><%= @raw_json %></div>
    <div style="display: none;" id="human_json"></div>
  <%- end %>

  <div class="endpoint-content">

    <%= simple_form_for @coverage, url: coverage_path, html: { class: 'form-horizontal' } do |f| %>
      <div class="form-inputs">
        <%= field_set_tag 'Payer' do %>
          <%= f.input :payer_id, label: 'ID', input_html: { style: 'width: 80%;' } %>
        <% end %>

        <%= field_set_tag 'Service' do %>
          <%= f.input :service_type, label: 'Code', input_html: { style: 'width: 80%;' } %>
        <% end %>

        <%= field_set_tag 'Provider' do %>
          <%= f.input :provider_npi, label: 'NPI' %>
          <%= f.input :provider_first_name, label: 'First Name' %>
          <%= f.input :provider_last_name, label: 'Last Name' %>
        <% end %>

        <%= field_set_tag 'Member' do %>
          <%= f.input :member_id, label: 'ID' %>
          <%= f.input :member_first_name, label: 'First Name' %>
          <%= f.input :member_last_name, label: 'Last Name' %>
          <%= f.input :member_dob, label: 'DOB' %>
        <% end %>
      </div>

      <div class="form-actions">
        <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
      </div>

    <%- end %>
  </div>
</div>