config/routes.rb
EligibleRailsDemo::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resource :settings, only: [:edit, :update]

  resources :providers
  resources :enrollments
  resource :demographics, only: [:new, :create]
  resource :coverage, only: [:new, :create], controller: :coverage
  resources :claims, only: [:index]
  resources :tickets
  resource :x12, only: [:new, :create], controller: :x12

  resources :payers, only: [:index]
  resources :service_types, only: [:index]

  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/payer.rb
class Payer < ActiveRecord::Base
  has_many :payer_names, dependent: :destroy
  validates :payer_id, presence: true, uniqueness: true

  accepts_nested_attributes_for :payer_names, reject_if: :all_blank, allow_destroy: true
end

app/models/payer_name.rb
class PayerName < ActiveRecord::Base
  belongs_to :payer


end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user

  validates :npi, presence: true, uniqueness: { scope: :user_id }
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  validates :service_type_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :providers, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :api_key, uniqueness: true
  validates :api_key, presence: true, on: :update

  def ready_for_api_calls?
    !api_key.blank?
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_filter :authenticate_user!, :ask_for_api_key
end

app/controllers/demographics_controller.rb
class DemographicsController < ApplicationController
  before_filter :authenticate_user!, :ask_for_api_key

  def new
    @demographic = Eligible::Demographic.new
  end

  def create
    @demographic = Eligible::Demographic.new(demographic_params)
    @demographic.api_key = current_user.api_key

    if @demographic.valid?
      begin
        @raw_json = RestClient.get(ELIGIBLE_DEMOGRAPHIC_URL, params: @demographic.to_hash(false))
        @json = JSON(@raw_json)
        if @json['error']
          flash[:warning] = @json['error']['reject_reason_description'].presence
        else
          @full_name = parse_full_name(@json)
          @dob = parse_dob(@json)
          @address = parse_address(@json)
        end
      rescue Exception => ex
        flash[:warning] = ex.message
      end
    end

    render :new
  end

  private

  def demographic_params
    params.require(:eligible_demographic).permit(:payer_id, :provider_npi, :provider_first_name, :provider_last_name,
                                                 :member_id, :member_first_name, :member_last_name, :member_dob)
  end

  def parse_full_name(json)
    first_name = json['subscriber']['first_name'].presence.humanize
    last_name = json['subscriber']['last_name'].presence.humanize
    "#{first_name} #{last_name}"
  end

  def parse_dob(json)
    json['subscriber']['dob']
  end

  def parse_address(json)
    address = {}
    address[:street] = [json['subscriber']['address']['street_line_1']]
    address[:street] << json['subscriber']['address']['street_line_2'] if json['subscriber']['address']['street_line_2']
    address[:city] = json['subscriber']['address']['city']
    address[:state] = json['subscriber']['address']['state']
    address[:zip] = json['subscriber']['address']['zip']
    address
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :ask_for_api_key, if: :user_signed_in?


end

app/controllers/x12_controller.rb
class X12Controller < ApplicationController
  before_filter :authenticate_user!, :ask_for_api_key

  def new
    @x12 = Eligible::X12.new
  end

  def create
    @x12 = Eligible::X12.new(x12_params)
    @x12.api_key = current_user.api_key

    if @x12.valid?
      begin
        @result = RestClient.get(ELIGIBLE_X12_URL, params: @x12.to_hash(false))
      rescue Exception => ex
        flash[:warning] = ex.message
      end
    end

    render :new
  end

  private

  def x12_params
    params.require(:eligible_x12).permit(:x12)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/coverage_helper.rb
module CoverageHelper
end

app/helpers/demographics_helper.rb
module DemographicsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payers_helper.rb
module PayersHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/x12_helper.rb
module X12Helper
end

app/views/demographics/new.html.erb
<%- content_for :javascript do %>
  <%= javascript_include_tag 'demographics' %>
<%- end %>

<div class="main-content">
  <h1>Demographics</h1>

  <%- if @json && @json['error'].nil? %>
    <h3>Demographics</h3>
    <table class="table table-hover">
      <tr>
        <th>Full Name</th>
        <td><%= @full_name %></td>
      </tr>
      <tr>
        <th>DOB</th>
        <td><%= @dob %></td>
      </tr>
      <tr>
        <th>Street</th>
        <td><%= raw @address[:street].join("<br/>") %></td>
      </tr>
      <tr>
        <th>City</th>
        <td><%= @address[:city] %></td>
      </tr>
      <tr>
        <th>State</th>
        <td><%= @address[:state] %></td>
      </tr>
      <tr>
        <th>ZIP</th>
        <td><%= @address[:zip] %></td>
      </tr>
    </table>
  <%- end %>

  <%- unless @raw_json.blank? %>
    <div style="display: none;" id="raw_json"><%= @raw_json %></div>
    <div id="human_json"></div>
  <%- end %>

  <div class="endpoint-content">


    <%= simple_form_for @demographic, url: demographics_path, html: { class: 'form-horizontal' } do |f| %>
      <div class="form-inputs">
        <%= field_set_tag 'Payer' do %>
          <%= f.input :payer_id, label: 'ID', input_html: { style: 'width: 80%;' } %>
        <% end %>

        <%= field_set_tag 'Provider' do %>
          <%= f.input :provider_npi, label: 'NPI' %>
          <%= f.input :provider_first_name, label: 'First Name' %>
          <%= f.input :provider_last_name, label: 'Last Name' %>
        <% end %>

        <%= field_set_tag 'Member' do %>
          <%= f.input :member_id, label: 'ID' %>
          <%= f.input :member_first_name, label: 'First Name' %>
          <%= f.input :member_last_name, label: 'Last Name' %>
          <%= f.input :member_dob, label: 'DOB' %>
        <% end %>
      </div>

      <div class="form-actions">
        <%= f.submit "Submit", class: "btn btn-large btn-primary" %>
      </div>

    <%- end %>
  </div>
</div>