config/routes.rb
EligibleRailsDemo::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resource :settings, only: [:edit, :update]

  resources :providers
  resources :enrollments
  resource :demographics, only: [:new, :create]
  resource :coverage, only: [:new, :create], controller: :coverage
  resources :claims, only: [:index]
  resources :tickets
  resource :x12, only: [:new, :create], controller: :x12

  resources :payers, only: [:index]
  resources :service_types, only: [:index]

  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/payer.rb
class Payer < ActiveRecord::Base
  has_many :payer_names, dependent: :destroy
  validates :payer_id, presence: true, uniqueness: true

  accepts_nested_attributes_for :payer_names, reject_if: :all_blank, allow_destroy: true
end

app/models/payer_name.rb
class PayerName < ActiveRecord::Base
  belongs_to :payer


end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :user

  validates :npi, presence: true, uniqueness: { scope: :user_id }
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/models/service_type.rb
class ServiceType < ActiveRecord::Base
  validates :service_type_id, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :providers, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :api_key, uniqueness: true
  validates :api_key, presence: true, on: :update

  def ready_for_api_calls?
    !api_key.blank?
  end

  def to_s
    "#{first_name} #{last_name}"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :ask_for_api_key, if: :user_signed_in?


end

app/controllers/x12_controller.rb
class X12Controller < ApplicationController
  before_filter :authenticate_user!, :ask_for_api_key

  def new
    @x12 = Eligible::X12.new
  end

  def create
    @x12 = Eligible::X12.new(x12_params)
    @x12.api_key = current_user.api_key

    if @x12.valid?
      begin
        @result = RestClient.get(ELIGIBLE_X12_URL, params: @x12.to_hash(false))
      rescue Exception => ex
        flash[:warning] = ex.message
      end
    end

    render :new
  end

  private

  def x12_params
    params.require(:eligible_x12).permit(:x12)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/claims_helper.rb
module ClaimsHelper
end

app/helpers/coverage_helper.rb
module CoverageHelper
end

app/helpers/demographics_helper.rb
module DemographicsHelper
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/payers_helper.rb
module PayersHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/service_types_helper.rb
module ServiceTypesHelper
end

app/helpers/settings_helper.rb
module SettingsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/x12_helper.rb
module X12Helper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Eligible Rails Demo APP</title>

  <%= stylesheet_link_tag "application", media: "all" %>
  <%= yield :stylesheets %>
  <%= javascript_include_tag "application" %>
  <%= yield :javascript %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Eligible Demo", root_path, class: 'brand' %>
      <div class="nav-collapse collapse">
        <%- if user_signed_in? %>
          <div class="dropdown pull-right">
            <!-- Link or button to toggle dropdown -->
            <a class="dropdown-toggle btn" data-toggle="dropdown" href="#"><%= current_user.first_name %></a>
            <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
              <li><a tabindex="-1" href="<%= edit_settings_path %>">Settings</a></li>
              <li><a tabindex="-1" href="<%= edit_user_registration_path %>">Profile</a></li>
              <li class="divider"></li>
              <li><a tabindex="-1" href="<%= destroy_user_session_path %>" data-method="delete">Logout</a></li>
            </ul>
          </div>
        <%- else %>
          <p class="navbar-text pull-right">
            <%= link_to "Register", new_user_registration_path %>
            |
            <%= link_to "Log In", new_user_session_path %>
          </p>
        <%- end %>
        <ul class="nav">
          <%- if user_signed_in? %>
            <li class="<%= params[:controller] == 'providers' ? 'active' : '' %>">
              <%= link_to("Providers", providers_path) %>
            </li>
            <!--<li class="<%= params[:controller] == 'enrollments' ? 'active' : '' %>">-->
              <!--<%= link_to("Enrollments", enrollments_path) %>-->
            <!--</li>-->
            <li class="<%= params[:controller] == 'demographics' ? 'active' : '' %>">
              <%= link_to("Demographics", new_demographics_path) %>
            </li>
            <li class="<%= params[:controller] == 'coverage' ? 'active' : '' %>">
              <%= link_to("Coverage", new_coverage_path) %>
            </li>
            <!--<li class="<%= params[:controller] == 'claims' ? 'active' : '' %>">-->
              <!--<%= link_to("Claims", claims_path) %>-->
            <!--</li>-->
            <!--<li class="<%= params[:controller] == 'tickets' ? 'active' : '' %>">-->
              <!--<%= link_to("Tickets", tickets_path) %>-->
            <!--</li>-->
            <li class="<%= params[:controller] == 'x12' ? 'active' : '' %>">
              <%= link_to("X12", new_x12_path) %>
            </li>
          <%- end %>
        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>


<div class="container">

  <%= render '/shared/flash', flash: flash %>

  <%= yield %>

</div>

</body>
</html>

app/views/shared/_flash.html.erb
<%- if flash.any? %>
  <%- flash.keys.each do |flash_key| %>
    <%- next if flash_key.to_s == 'timedout' %>
    <div class="alert alert-<%= flash_key %>">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.discard(flash_key) %>
    </div>
  <%- end %>
<%- end %>

app/views/shared/_form_errors.html.erb
<%- if object.errors.any? %>
  <div class="error_explanation">
    <h2>Please, fix the <%= pluralize(object.errors.count, "error") %></h2>

    <ul>
      <%- object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <%- end %>
    </ul>

  </div>
<%- end %>

app/views/shared/_simple_form_errors.html.erb
<%- if f.error_notification %>
  <div class="alert alert-error fade in">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <div class="error_notification"><%= f.error_notification %></div>
    <%- if f.object.errors[:base].size > 0 %>
      <ul>
        <%- f.object.errors[:base].each do |error| %>
          <li><%= error %></li>
        <%- end %>
      </ul>
    <%- end %>
  </div>
<%- end %>